'@context':
  description: The context URL
  type: string
  example: https://schema.org/
'@type':
  description: The type of the list
  type: string
  example: collection
ItemList:
  description: The list of products
  type: product[]
pagination:
  description: Pagination object
  type: pagination